runtime: nodejs12
service: convatec-ob-ui-test

handlers:
- url: /api/.*
  script: auto
- url: /
  static_files: build/index.html
  upload: build/index.html
- url: /
  static_dir: build
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
